apiVersion: v1
kind: Service
metadata:
  name: gitlab-webservice-nodeport
  namespace: gitlab
spec:
  type: NodePort
  ports:
    - port: 8181
      targetPort: 8181
      nodePort: 30130
      protocol: TCP
  selector:
    app: webservice
