# apiVersion: apps.gitlab.com/v1beta1
# kind: GitLab
# metadata:
#   name: gitlab
#   namespace: gitlab
# spec:
#   chart:
#     version: "8.11.1"
#     values:
#       edition: ce
#       global:
#         hosts:
#           domain: gitlab.local
#           https: false
#         ingress:
#           enabled: true
#           configureCertmanager: true
#       certmanager-issuer:
#         email: no-reply@gitlab.local
# apiVersion: apps.gitlab.com/v1beta1
# kind: GitLab
# metadata:
#   name: gitlab
#   namespace: gitlab
# spec:
#   chart:
#     version: "8.11.1" 
#     values:
#       edition: ce
#       global:
#         hosts:
#           domain: gitlab.local
#           https: false
#         ingress:
#           enabled: true
#         email:
#           from: no-reply@gitlab.local
#         redis:
#           enabled: true
#         resources:
#           requests:
#             cpu: 50m
#             memory: 50Mi
#           limits:
#             cpu: 200m
#             memory: 200Mi
#       nginx-ingress:
#         enabled: false
#       certmanager:
#         install: false
#       prometheus:
#         install: false
#       gitlab-runner:
#         install: false
#       registry:
#         enabled: false
#       postgresql:
#         install: true
#         resources:
#           requests:
#             cpu: 50m
#             memory: 50Mi
#           limits:
#             cpu: 200m
#             memory: 200Mi
#       redis:
#         install: true
#         resources:
#           requests:
#             cpu: 50m
#             memory: 50Mi
#           limits:
#             cpu: 200m
#             memory: 200Mi
#         gitlab-shell:
#           minReplicas: 1
#           maxReplicas: 1
#         kas:
#           minReplicas: 1
#           maxReplicas: 1
#         certmanager-issuer:
#           email:
#             from: no-reply@gitlab.local

apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
  namespace: gitlab
spec:
  chart:
    version: "8.11.1"
    values:
      global:
        edition: ce
        ingress:
          configureCertmanager: false
          class: "nginx"
        hosts:
          domain: localhost
          externalIP: 0.0.0.0
          https: false
        rails:
          bootsnap:
            enabled: false
        shell:
          port: 32022
      certmanager:
        install: false
      nginx-ingress:
        enabled: false
      prometheus:
        install: false
      gitlab-runner:
        install: false
      gitlab:
        webservice:
          minReplicas: 1
          maxReplicas: 1
        sidekiq:
          minReplicas: 1
          maxReplicas: 1
        gitlab-shell:
          minReplicas: 1
          maxReplicas: 1
          service:
            type: NodePort
            nodePort: 32022
      registry:
        hpa:
          minReplicas: 1
          maxReplicas: 1
