# - name: Add cert-manager Helm repository
#   kubernetes.core.helm_repository:
#     name: jetstack
#     repo_url: https://charts.jetstack.io
#     state: present
#
# - name: Create cert-manager namespace
#   kubernetes.core.k8s:
#     kind: Namespace
#     name: cert-manager
#     state: present
#
# - name: Install cert-manager CRDs
#   kubernetes.core.k8s:
#     src: https://github.com/cert-manager/cert-manager/releases/download/v1.13.2/cert-manager.crds.yaml
#     state: present
#
# - name: Install cert-manager
#   kubernetes.core.k8s:
#     src: https://github.com/cert-manager/cert-manager/releases/download/v1.13.2/cert-manager.yaml
#     state: present
#
# - name: Wait for cert-manager deployment to be ready
#   kubernetes.core.k8s_info:
#     kind: Deployment
#     name: cert-manager
#     namespace: cert-manager
#     wait: yes
#     wait_condition:
#       type: Available
#       status: "True"
#
# - name: Add GitLab Helm repository
#   kubernetes.core.helm_repository:
#     name: gitlab
#     repo_url: https://charts.gitlab.io/
#     state: present
#
# - name: Create gitlab-system namespace
#   kubernetes.core.k8s:
#     kind: Namespace
#     name: gitlab
#     state: present
#
# - name: Install GitLab operator
#   kubernetes.core.helm:
#     name: gitlab-operator
#     chart_ref: gitlab/gitlab-operator
#     release_namespace: gitlab
#     wait: true

- name: Add GitLab Helm repository
  kubernetes.core.helm_repository:
    name: gitlab
    repo_url: https://charts.gitlab.io/
    state: present

- name: Create gitlab namespace
  kubernetes.core.k8s:
    kind: Namespace
    name: gitlab
    state: present

- name: Create GitLab values file
  copy:
    dest: /tmp/gitlab-values.yml
    src: "{{ playbook_dir }}/../gitlab_config/gitlab-values.yml"

- name: Install GitLab using Helm
  kubernetes.core.helm:
    name: gitlab
    chart_ref: gitlab/gitlab
    release_namespace: gitlab
    values_files:
      - /tmp/gitlab-values.yml
    wait: true
    timeout: 1000s

- name: Apply a rediction webservice service
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', playbook_dir + '/../gitlab_config/gitlab-webservice-service.yml') | from_yaml }}"
    namespace: gitlab
    wait: true
    wait_timeout: 1000

- name: Apply a rediction shell service
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', playbook_dir + '/../gitlab_config/gitlab-shell-service.yml') | from_yaml }}"
    namespace: gitlab
    wait: true
    wait_timeout: 1000

- name: Get GitLab initial root password
  kubernetes.core.k8s_info:
    kind: Secret
    name: "gitlab-gitlab-initial-root-password"
    namespace: gitlab
  register: gitlab_secret


- name: Log GitLab root credentials
  ansible.builtin.debug:
    msg: "Username: root || Password: {{ gitlab_secret.resources[0].data.password | b64decode }}"

