- name: Install gitlab module for python
  pip:
    name: python-gitlab
    break_system_packages: true

- name: Create public GitLab project
  community.general.gitlab_project:
    api_url: "http://104.248.119.73:8181/"
    api_username: "root"
    api_password: "XTpU2I03mUHIV7r0R6oY34jQscwzNOGv0yA6xuaCYWAyZusd0Ytih3napZj8afmk"
    name: "my-public-repo"
    visibility: "public"
    initialize_with_readme: true
    state: present
    validate_certs: false

- name: Configure git repository
  git:
    repo: "http://143.110.238.90:8181/root/my-public-repo.git"
    dest: "/tmp/my-public-repo"
    remote: "origin"
    force: yes
    update: yes
    version: main

- name: Copy files from /home/repo to the repository
  copy:
    src: "/home/repo/"
    dest: "/tmp/my-public-repo/"
    remote_src: yes

- name: Configure git user
  git_config:
    name: user.name
    scope: local
    repo: /tmp/my-public-repo
    value: "root"

- name: Configure git email
  git_config:
    name: user.email
    scope: local
    repo: /tmp/my-public-repo
    value: "root@localhost"

- name: Add and commit files
  shell:
    cmd: |
      cd /tmp/my-public-repo
      git add .
      git commit -m "Adding files from /home/repo"
  args:
    chdir: /tmp/my-public-repo

- name: Push to GitLab repository
  shell:
    cmd: |
      cd /tmp/my-public-repo
      git push http://root:XTpU2I03mUHIV7r0R6oY34jQscwzNOGv0yA6xuaCYWAyZusd0Ytih3napZj8afmk@143.110.238.90:8181/root/my-public-repo.git main
  args:
    chdir: /tmp/my-public-repo

