# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: will-application
  namespace: dev
spec:
  selector:
    matchLabels:
      app: will-application
  replicas: 1
  template:
    metadata:
      labels:
        app: will-application
    spec:
      containers:
      - name: will-application
        image: wil42/playground:v1
      restartPolicy: Always
---

# https://kubernetes.io/docs/concepts/services-networking/service/

apiVersion: v1
kind: Service
metadata:
  name: application-service
  namespace: dev
spec:
  selector:
    app: will-application
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: 30088
    port: 8888
