apiVersion: v1
kind: Service
metadata:
  name: gitlab-webservice-nodeport
  namespace: gitlab
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8181
      nodePort: 30081
      protocol: TCP

  selector:
    app: webservice
    gitlab.com/webservice-name: default
    release: gitlab
