apiVersion: v1
kind: Service
metadata:
  name: gitlab-webservice-nodeport
  namespace: gitlab
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31123
      protocol: TCP
  selector:
    app: gitlab
    component: webservice
