apiVersion: v1
kind: Service
metadata:
  name: gitlab-shell-nodeport
  namespace: gitlab
spec:
  type: NodePort
  ports:
    - protocol: TCP
      targetPort: 22
      port: 22
      nodePort: 32022
  selector:
    app: gitlab
    component: gitlab-shell
