gitlabUrl: http://gitlab-webservice-default.gitlab.svc.cluster.local:8181/
rbac:
  create: true
  clusterWideAccess: true
  rules:
    - resources: ["pods", "pods/exec", "pods/attach", "secrets", "configmaps"]
      verbs: ["get", "list", "watch", "create", "patch", "delete"]
runners:
  privileged: true
  config: |
    [[runners]]
      [runners.kubernetes]
        namespace = "gitlab"
        image = "ubuntu:22.04"
        privileged = true
        service_account = "gitlab-runner"

