apiVersion: v1
kind: Service
metadata:
  name: gitlab-shell-nodeport
  namespace: gitlab
spec:
  type: NodePort
  ports:
    - protocol: TCP
      targetPort: 2222
      port: 22
      nodePort: 30022
  selector:
    app: gitlab-shell
    release: gitlab
