# apiVersion: v1
# kind: Service
# metadata:
#   name: gitlab-webservice-nodeport
#   namespace: gitlab
# spec:
#   type: NodePort
#   ports:
#     - port: 8181
#       targetPort: 8181
#       nodePort: 30130
#       protocol: TCP
#   selector:
#     app: gitlab-webhook-service

apiVersion: v1
kind: Service
metadata:
  name: gitlab-webservice-nodeport
  namespace: gitlab
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30130
    protocol: TCP
    name: http
  selector:
    app: webservice
    release: gitlab
