global:
  edition: ce
  ingress:
    configureCertmanager: false
    class: "nginx"
  hosts:
    # domain: localhost
    # externalIP: 0.0.0.0
    https: false
  rails:
    bootsnap:
      enabled: false
  shell:
    port: 32022
certmanager:
  install: false
nginx-ingress:
  enabled: false
prometheus:
  install: false
gitlab-runner:
  install: true
gitlab:
  webservice:
    minReplicas: 1
    maxReplicas: 1
  sidekiq:
    minReplicas: 1
    maxReplicas: 1
  gitlab-shell:
    minReplicas: 1
    maxReplicas: 1
  gitlab-runner:
    minReplicas: 1
    maxReplicas: 1
registry:
  hpa:
    minReplicas: 1
    maxReplicas: 1
